services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
        restart: always
        networks:
          - main
        ports:
          - 9200:9200
        environment:
          - discovery.type=single-node
networks:
  main: